config/routes.rb
Rails.application.routes.draw do
  resources :yfcases
  root to: "yfcases#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/yfcase.rb
class Yfcase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/yfcases_controller.rb
class YfcasesController < ApplicationController
  before_action :set_yfcase, only: %i[ show edit update destroy ]

  # GET /yfcases or /yfcases.json
  def index
    @yfcases = Yfcase.all
  end

  # GET /yfcases/1 or /yfcases/1.json
  def show
  end

  # GET /yfcases/new
  def new
    @yfcase = Yfcase.new
  end

  # GET /yfcases/1/edit
  def edit
  end

  # POST /yfcases or /yfcases.json
  def create
    @yfcase = Yfcase.new(yfcase_params)

    respond_to do |format|
      if @yfcase.save
        format.html { redirect_to @yfcase, notice: "Yfcase was successfully created." }
        format.json { render :show, status: :created, location: @yfcase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @yfcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yfcases/1 or /yfcases/1.json
  def update
    respond_to do |format|
      if @yfcase.update(yfcase_params)
        format.html { redirect_to @yfcase, notice: "Yfcase was successfully updated." }
        format.json { render :show, status: :ok, location: @yfcase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @yfcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yfcases/1 or /yfcases/1.json
  def destroy
    @yfcase.destroy
    respond_to do |format|
      format.html { redirect_to yfcases_url, notice: "Yfcase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yfcase
      @yfcase = Yfcase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def yfcase_params
      params.require(:yfcase).permit(:yfcaseCaseNumber)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yfcases_helper.rb
module YfcasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yangfurails6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/yfcases/_form.html.erb
<%= form_with(model: yfcase) do |form| %>
  <% if yfcase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yfcase.errors.count, "error") %> prohibited this yfcase from being saved:</h2>

      <ul>
        <% yfcase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :yfcaseCaseNumber %>
    <%= form.text_field :yfcaseCaseNumber %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/yfcases/edit.html.erb
<h1>Editing Yfcase</h1>

<%= render 'form', yfcase: @yfcase %>

<%= link_to 'Show', @yfcase %> |
<%= link_to 'Back', yfcases_path %>

app/views/yfcases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Yfcases</h1>

<table>
  <thead>
    <tr>
      <th>Yfcasecasenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yfcases.each do |yfcase| %>
      <tr>
        <td><%= yfcase.yfcaseCaseNumber %></td>
        <td><%= link_to 'Show', yfcase %></td>
        <td><%= link_to 'Edit', edit_yfcase_path(yfcase) %></td>
        <td><%= link_to 'Destroy', yfcase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yfcase', new_yfcase_path %>

app/views/yfcases/new.html.erb
<h1>New Yfcase</h1>

<%= render 'form', yfcase: @yfcase %>

<%= link_to 'Back', yfcases_path %>

app/views/yfcases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Yfcasecasenumber:</strong>
  <%= @yfcase.yfcaseCaseNumber %>
</p>

<%= link_to 'Edit', edit_yfcase_path(@yfcase) %> |
<%= link_to 'Back', yfcases_path %>